// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljmgnlpgmbzqmpaavpvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbWdubHBnbWJ6cW1wYWF2cHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTMwNzYsImV4cCI6MjA2NzIyOTA3Nn0.PDSPkK9EOeIo6JJk29EzFRzmAc0kWj5B_eurIAaNO8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});